using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using System.Runtime.InteropServices;
using Blessing.Gameplay.Characters;
using Blessing.Gameplay.SkillsAndMagic;
using Unity.Netcode;

namespace Blessing.Gameplay.Characters
{
    public class CharacterMana : NetworkBehaviour
    {
        // Tentar criar a classe sem usar uma MonoBehaviour
        // public event EventHandler OnHealthChanged;
        protected IEnumerator coroutine;
        [SerializeField] protected ManaSpectrum manaReserve;
        [SerializeField] ManaSpectrum reserveMax;
        [SerializeField] protected int statsMultiplier = 5;
        [Tooltip("Mana Regenerated by time")][SerializeField] protected int manaRegen = 2;
        [SerializeField] protected float manaRegenTime = 0.5f;
        private bool isActive = true;

        // Start is called before the first frame update
        void Awake()
        {
            InitializeManaReserve();
        }

        void Start()
        {
            
        }
    
        private void InitializeManaReserve()
        {
            manaReserve = new ManaSpectrum(new Mana[]
            {
                    new(ManaColor.White, 50),
                    new(ManaColor.Red, 50), 
                    new(ManaColor.Green, 50), 
                    new(ManaColor.Blue, 50),
                    new(ManaColor.Black, 50)
            });

            reserveMax = new ManaSpectrum(new Mana[]
            {
                    new(ManaColor.White, 100),
                    new(ManaColor.Red, 100), 
                    new(ManaColor.Green, 100), 
                    new(ManaColor.Blue, 100),
                    new(ManaColor.Black, 100)
            });

            coroutine = ChangeManaByTime();
            StartCoroutine(coroutine);
        }

        public void SetManaParameters(CharacterStats stats)
        {
            // Set Max Values
            
            // White Mana Max, TODO:
            reserveMax.SetValue(ManaColor.White, 100);

            // Red Mana Max value comes from Strength
            reserveMax.SetValue(ManaColor.Red, stats.Strength * statsMultiplier);

            // Green Mana Max value comes from Constitution
            reserveMax.SetValue(ManaColor.Green, stats.Constitution * statsMultiplier);

            // Blue Mana Max value comes from Wisdom
            reserveMax.SetValue(ManaColor.Blue, stats.Wisdom * statsMultiplier);

            // Black Mana Max, TODO:
            reserveMax.SetValue(ManaColor.Black, 100);
            
            // Time to regenerate mana comes from total white mana, more white mana, faster mana regen

            if (manaReserve.GetValue(ManaColor.White) == 0)
                manaRegenTime = 50;
            else
                manaRegenTime = 50 / manaReserve.GetValue(ManaColor.White);

            // Mana gain by each mana regen cycle
            // manaRegenTime = 2
        }

        public void SpendMana(ManaColor color, int manaAmount)
        {
            if (manaAmount <= 0) return;

            int manaValue = manaReserve.GetValue(color);

            manaValue -= manaAmount;

            // Don't let health be negative
            if (manaValue < 0) manaValue = 0;
            
            manaReserve.SetValue(color, manaValue);
        }

        public bool SpendManaSpectrum(ManaSpectrum manaSpectrumCost)
        {
            //Check if has enough mana to spend in manaReserve
            bool hasEnoughMana = true;
            foreach (ManaColor manaColor in Enum.GetValues(typeof(ManaColor)))
            {
                if (manaReserve.GetValue(manaColor) < manaSpectrumCost.GetValue(manaColor))
                    hasEnoughMana = false;
            }

            // Early exit if hasEnoughMana is false
            if (!hasEnoughMana) return false;

            // Spent mana
            foreach (ManaColor manaColor in Enum.GetValues(typeof(ManaColor)))
            {
                int newValue = manaReserve.GetValue(manaColor) - manaSpectrumCost.GetValue(manaColor);
                
                manaReserve.SetValue(manaColor, newValue);
            }

            return true;
        }

        public void ReceiveMana(ManaColor color, int manaAmount)
        {
            if (manaAmount <= 0) return;

            int newValue = manaReserve.GetValue(color) + manaAmount;

            // Check for max color mana value
            if (reserveMax.GetValue(color) < newValue)
                newValue = reserveMax.GetValue(color);

            manaReserve.SetValue(color, newValue);
        }
        public IEnumerator ChangeManaByTime()
        {
            while (isActive)
            {
                foreach (ManaColor manaColor in Enum.GetValues(typeof(ManaColor)))
                {
                    
                    int manaDiff = manaReserve.GetValue(manaColor) - reserveMax.GetValue(manaColor);

                    // Current Value is less than max, should regen mana
                    if (manaDiff < 0)
                        ReceiveMana(manaColor, manaRegen);

                    // Current Value is more than max, mana will decay
                    if (manaDiff > 0)
                        SpendMana(manaColor, manaRegen);
                }

                yield return new WaitForSeconds(manaRegenTime);
            }
        }
    }
}
